export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const LOAD_ORGAN = 'LOAD_ORGAN';
export const CHANGE_DOMAIN = 'CHANGE_DOMAIN';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOAD_MODULE = 'LOAD_MODULE';
export const ACTIVE_MODULE = 'ACTIVE_MODULE';
export const LOAD_MENU = 'LOAD_MENU';
export const ACTIVE_MENU = 'ACTIVE_MENU';
export const ACTIVE_MENU_ITEM = 'ACTIVE_MENU_ITEM';
export const CLOSE_QUICK_MENU_ITEM = 'CLOSE_QUICK_MENU_ITEM';
export const CLOSE_ALL_QUICK_MENU_ITEM = 'CLOSE_ALL_QUICK_MENU_ITEM';
export const CLEAR_QUICK_MENU_ITEM = 'CLEAR_QUICK_MENU_ITEM';